### ISSUE TITLE
demo canister values dont pass verification

### ISSUE THREAD

**Issue by letmejustputthishere** [nomeata/motoko-merkle-tree#4]
https://wpsi7-7aaaa-aaaai-acpzq-cai.ic0.app/get/moritz%20war%20hier

**Comment by nomeata** [comment]
Ah, probably due to percent-encoding of the keys in the url. I should simply forbid such keys in the demo :-D

**Comment by letmejustputthishere** [comment]
doesnt work with the default key either :(

**Comment by letmejustputthishere** [comment]
https://wpsi7-7aaaa-aaaai-acpzq-cai.ic0.app/get/some_key

**Comment by nomeata** [comment]
Ok, that looks like a bug. Thanks for checking!

**Comment by nomeata** [comment]
Ah, it does now!

What happened was that I changed the function that generates the HTML and upgraded the canister. But that of course means all the pages need to be re-certified. Added that to the `post_upgrade` hook now.
