### ISSUE TITLE
Bug. "Losing precision"

### ISSUE THREAD

**Issue by infu** [nomeata/motoko-merkle-tree#8]
Found a bug. It was hard to figure exactly what caused it, because the error isn't providing a lot of information:
"trapped explicitly: losing precision"

How to reproduce:
https://github.com/infu/certified-http
deploy locally and run test.blast

The library uses ic-certification and sha2. I believe it's not the SHA2 (used for hashing file contents)
The problem is in ic-certification, because the test fails only when paths are too long and doesn't depend on what the file contents are.

Paths currently get hashed with older SHA, probably in MerkleTree.mo and possibly use older base libraries, which at some point were found to produce this error. 

Shorty put, this will error
```
ct.put(["http_assets", Text.encodeUtf8("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa123364823232")], value)
```

**Comment by nomeata** [comment]
Thanks for the report.

This is a 59 byte string. Is that where it starts failing? I.e. if you make the path one letter shorter it succeeds? Or is it not minimal?

**Comment by infu** [comment]
Here is something close to the minimum "aaaaaaaaaaaaaaaaaaaaaaaaaaa0.765a" that errors
But if I change the 0 to 'a' it passes, so its not only the text length that matters (Haven't checked byte length)

**Comment by nomeata** [comment]
Ok, then the bid fiddling has issues. It’s 33 bytes, so maybe that helps to find the bug.

**Comment by nomeata** [comment]
Just to know where to look for the bug: Is it really the `ct.put` that traps, or possibly some later operation (such as creating a witness)?

**Comment by nomeata** [comment]
https://github.com/nomeata/ic-certification/blob/3f51849073d19d2ab46aaff3c4985bf8c60196a1/src/Dyadic.mo#L27C1-L27C1 is a candidate. I wonder if this should be
```
      let mask = 0xff >> Nat8.Nat(i % 8)
```

**Comment by nomeata** [comment]
Yes, that seems to be it.

**Comment by nomeata** [comment]
Fix published as 0.1.1

**Comment by infu** [comment]
I can confirm. My tests passed with 0.1.1

**Comment by timohanke** [comment]
> https://github.com/nomeata/ic-certification/blob/3f51849073d19d2ab46aaff3c4985bf8c60196a1/src/Dyadic.mo#L27C1-L27C1 is a candidate. I wonder if this should be
> 
> ```
> 
>       let mask = 0xff >> Nat8.Nat(i % 8)
> 
> ```
> 
> 
> 
> 

Wouldn't Nat8.fromIntWrap(i) be preferred?

**Comment by nomeata** [comment]
I guess it would be a bit faster maybe?
